# Generated by Django 5.2 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_alter_game_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
