# Generated by Django 5.2 on 2025-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_remove_game_image_game_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
    ]
